development:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'local_dev'
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'local_dev'
  host: localhost
  pool: 5
  timeout: 5000